### ISSUE TITLE
Criar CRUD Rating

### ISSUE THREAD

**Issue by herikLorencao** [zero28devs/cheffon-api-core#7]
Criar CRUD da entidade Rating do sistema.

**Comment by WesleyLeoncio** [comment]
Quando vai rodar os testes na aba do Maven o teste quebra e fala que ocorreu um erro na class TagSeriviceTeste no mock, tentei resolver e não consegui.

**Comment by herikLorencao** [comment]
De boa na reunião a gente tenta ver isso.
